// REDUX ACTION TYPES

export const SET_HISTORY = "SET_HISTORY";
export const RESET_HISTORY = "RESET_HISTORY";

export const SET_COMPONENT_LOADING = "SET_COMPONENT_LOADING";
export const CLOSE_COMPONENT_LOADING = "CLOSE_COMPONENT_LOADING";

export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const CLOSE_LOGIN_FORM = "CLOSE_LOGIN_FORM";

export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";

export const SET_OPEN_TOAST = "SET_OPEN_TOAST";
export const SET_CLOSE_TOAST = "SET_CLOSE_TOAST";

export const SET_ERROR = "SET_ERROR";
export const RESET_ERROR = "RESET_ERROR";
