// REDUX ACTION TYPES

export const SET_HISTORY = "SET_HISTORY";
export const RESET_HISTORY = "RESET_HISTORY";

export const SET_COMPONENT_LOADING = "SET_COMPONENT_LOADING";
export const CLOSE_COMPONENT_LOADING = "CLOSE_COMPONENT_LOADING";

export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";
export const CLOSE_LOGIN_FORM = "CLOSE_LOGIN_FORM";
export const SET_IS_LOGINED = "SET_IS_LOGINED";
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_SIGNUP = "SET_USER_SIGNUP";

export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";

export const SET_OPEN_TOAST = "SET_OPEN_TOAST";
export const SET_CLOSE_TOAST = "SET_CLOSE_TOAST";

export const SET_ERROR = "SET_ERROR";
export const RESET_ERROR = "RESET_ERROR";

export const SET_GROUP_VOCAS_LIST = "SET_GROUP_VOCAS_LIST";
export const SET_VOCA_OBJECT = "SET_VOCA_OBJECT";
export const ADD_GROUP_VOCAS_ITEM = "ADD_GROUP_VOCAS_ITEM";
export const REMOVE_GROUP_VOCAS_ITEM = "REMOVE_GROUP_VOCAS_ITEM";
export const RESET_GROUP_VOCAS_LIST = "RESET_GROUP_VOCAS_LIST";

export const SET_VOCABULARY_LIST = "SET_VOCAS_LIST";
export const SET_VOCABULARY_OBJECT = "SET_VOCABULARY_OBJECT";
export const ADD_VOCABULARY_INTO_LIST = "ADD_VOCABULARY_INTO_LIST";
export const REMOVE_VOCABULARY_FROM_LIST = "REMOVE_VOCABULARY_FROM_LIST";
